services:
  - type: web
    name: minecraft-site
    env: debian
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y php
    startCommand: php -S 0.0.0.0:10000
    autoDeploy: true
